### ISSUE TITLE
Setting unknown property: dosamigos\typeahead\TypeAhead::clientEvents

### ISSUE THREAD

**Issue by Mazorati** [2amigos/yii2-type-ahead-widget#11] opened 2015-09-14 16:25 UTC

**Comment by loktionov** [comment] 2015-10-15 13:32
There is a conflict between  yiisoft/yii2-gii and  2amigos/yii2-type-ahead-widget 1.1
I have an error when trying install 1.1
 Problem 1
    - Installation request for 2amigos/yii2-type-ahead-widget >=1.1 -> satisfiable by 2amigos/yii2-type-ahead-widget[1.1].
    - Conclusion: remove bower-asset/typeahead.js v0.10.5
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - Conclusion: don't install bower-asset/typeahead.js v0.10.5
    - Installation request for yiisoft/yii2-gii * -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].

**Comment by tonydspaniard** [comment] 2016-01-19 21:36
@loktionov the problem is with gii as it uses a lower version, not with the extension.

**Comment by tonydspaniard** [comment] 2016-01-19 21:36
@Mazorati i need more info, code sample?

**Comment by dzona** [comment] 2018-08-16 09:02
closing issue due to lack of information

**Closed by dzona** 2018-08-16 09:02 UTC
